<?php

/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\Grafanadashboards\Controllers;



use Icinga\Application\Modules\Module;
use Icinga\Module\Grafanadashboards\GrafanaHelper;
use Icinga\Module\Grafanadashboards\InstanceIniRepository;
use Icinga\Module\Grafanadashboards\JwtGrafanaModuleWrapper;
use Icinga\Module\Grafanadashboards\JwtHelper;
use Icinga\Module\Grafanadashboards\PermissionHelper;
use Icinga\Web\Notification;
use Icinga\Web\Url;
use ipl\Html\Html;
use ipl\Web\Compat\CompatController;
use ipl\Web\Widget\Icon;


class GrafanaController extends CompatController
{

    protected $name;
    protected $instance;

    /* @var $helper \Icinga\Module\Grafanadashboards\GrafanaHelper */
    protected $helper;
    protected $folder;
    protected $config;
    protected $token;
    protected $permissionHelper;


    public function init()
    {

        parent::init();
        $this->permissionHelper = new PermissionHelper();
        $this->name = $this->params->getRequired('name');
        $instanceRepository = new InstanceIniRepository();
        $this->instance = $instanceRepository->select()->where($instanceRepository->getIdentifierName(), $this->name)->fetchRow();
        if($this->instance !== false){
            if(!$this->permissionHelper->hasPermissionForInstance($this->instance->name)){
                throw new \Exception("You don't have permission to access Grafana for instance ".$this->instance->name);
            }
            $module = Module::get('grafanadashboards');
            $cacheDir = $module->getConfigDir().DIRECTORY_SEPARATOR."cache";
            $this->folder = $this->getParam('folder');
            if(isset($this->instance->url) && isset($this->instance->apikey)){
                $this->helper =  new GrafanaHelper(
                    $this->instance->name,
                    $this->instance->url,
                    $this->instance->apikey,
                    $this->instance->disable_ssl =='1',
                    $cacheDir
                );

            }else{
                throw new \Exception("Configure Module grafanadashboards first!");
            }
            if($this->instance->type === "jwt"){
                $username = $this->Auth()->getUser()->getUsername();
                $module = Module::get('grafanadashboards');
                $pkiDir = $module->getConfig()->get('settings','pkidir',$module->getConfigDir().DIRECTORY_SEPARATOR."pki");
                $jwt = new JwtHelper($this->instance->name,$username,100,$username."@jwtlogin",$pkiDir);
                $this->token = $jwt->generateJwtToken();
            }elseif($this->instance->type === "grafanamodule"){
                $this->token = JwtGrafanaModuleWrapper::getJwtToken();
            }else{
                $this->token = false;
            }


        }
        $this->initTabs();



    }

    public function indexAction()
    {

        $this->addContent(Html::tag('h1',null,'Folders'));

        if($this->instance !== false && $this->instance !== null){


            $this->addContent(Html::tag('h2',null,t('Instance')." ".$this->instance->name));


            $items = $this->helper->provideMenuItems();
            $instanceUrl = $this->instance->url;

            if($this->token !== false){
                $instanceUrl=$instanceUrl."?".'auth_token='.$this->token;
            }
            $a = Html::tag("a",['class'=>"dashboard-link",'target'=>'_blank','href'=> $instanceUrl]);
            $div = Html::tag("div",['class'=>"link-icon"]);
            $i = new Icon("area-chart",[ 'aria-hidden' => 1]);

            $div->add($i);
            $a->add($div);

            $div_link_meta = Html::tag("div",['class'=>"link-meta"]);
            $div_link_label = Html::tag("div",['class'=>"link-label"],'Grafana');
            $div_link_description = Html::tag("div",['class'=>"link-description"],"Goto Grafana");
            $div_link_meta->add($div_link_label);
            $div_link_meta->add($div_link_description);
            $a->add($div_link_meta);
            $this->addContent($a);
            if($items ===false){
                $this->addContent(Html::tag('p',null,'Currently there is nothing available'));
                return;
            }
            $items = $this->permissionHelper->filterMenuFolders($items);



            foreach ($items as $item){


                $finalUrl = Url::fromPath('grafanadashboards/grafana/folder',['folder'=>$item,'name'=>$this->instance->name]);

                $a = Html::tag("a",['class'=>"dashboard-link",'href'=> $finalUrl]);
                $div = Html::tag("div",['class'=>"link-icon"]);
                $i = new Icon("folder",[ 'aria-hidden' => 1]);

                $div->add($i);
                $a->add($div);
                $div_link_meta = Html::tag("div",['class'=>"link-meta"]);
                $div_link_label = Html::tag("div",['class'=>"link-label"],$item);
                $div_link_description = Html::tag("div",['class'=>"link-description"],"View Folder {$item}");
                $div_link_meta->add($div_link_label);
                $div_link_meta->add($div_link_description);
                $a->add($div_link_meta);
                $this->addContent($a);

            }
            if($this->permissionHelper->hasPermissionToRebuild()){
                $finalUrl = Url::fromPath('grafanadashboards/grafana/rebuild',['name'=>$this->instance->name]);

                $a = Html::tag("a",['class'=>"dashboard-link",'href'=> $finalUrl]);
                $div = Html::tag("div",['class'=>"link-icon"]);
                $i = new Icon("rotate-right",[ 'aria-hidden' => 1]);

                $div->add($i);
                $a->add($div);
                $div_link_meta = Html::tag("div",['class'=>"link-meta"]);
                $div_link_label = Html::tag("div",['class'=>"link-label"],"Reload from Grafana");
                $div_link_description = Html::tag("div",['class'=>"link-description"],"Reload structure from Grafana");
                $div_link_meta->add($div_link_label);
                $div_link_meta->add($div_link_description);
                $a->add($div_link_meta);
                $this->addContent($a);

            }

        }




    }



    public function dashboardAction(){
        $uid = $this->getParam('uid');
        $this->getTabs()->activate($uid);
        $dashboard = $this->helper->getDashboardByUid($uid);

        //Logger::error(json_encode($this->helper->getApiConnection()->getDashboard($uid)));
        if($dashboard ===false){
            $this->addContent(Html::tag('p',null,'Currently there is nothing available'));
            return;
        }
        if(!$this->permissionHelper->hasPermissionForDashboard($dashboard['title'])){
            throw new \Exception("You don't have permission to access this Dashboard");
        }

        $instanceUrl = $this->instance->url;
        if(strpos($instanceUrl,"/grafana") !== false && strpos($dashboard['url'],"/grafana") === 0){
            $dashboard['url'] = preg_replace('/' . preg_quote("/grafana", '/') . '/', "", $dashboard['url'], 1);
        }
        $url = $instanceUrl.$dashboard['url']."?orgId=1&from=now-24h&to=now&theme=light&kiosk";
        if($this->token !== false){
            $url=$url."&".'auth_token='.$this->token;
        }
        $this->addContent(Html::tag('iframe', ['src'=>$url, 'id'=>'myIframe', 'width'=>'100%', 'height'=>'100%','frameborder'=>'no']),"<p>Your browser does not support iframes.</p>");
        $this->content->setAttribute("class","iframe-container");

    }
    public function rebuildAction(){
        $this->assertPermission('grafanadashboards/rebuild');
        if($this->helper->rebuildCache()){
            Notification::success("Grafana Cache rebuilt");
        }else{
            Notification::error("Grafana Cache not rebuilt");
        }

        $this->redirectNow(\ipl\Web\Url::fromPath('grafanadashboards/grafana',['name'=>$this->instance->name]));

    }
    public function folderAction()
    {
        if(!$this->permissionHelper->hasPermissionForFolder($this->folder)){
            throw new \Exception("You don't have permission to access this Folder");
        }

        $dashboards = $this->helper->getDashboardsByFolder($this->folder);

        $dashboards = $this->permissionHelper->filterDashboards($dashboards);

        if($dashboards ===false){
            $this->addContent(Html::tag('p',null,'Currently there is nothing available'));
            return;
        }
        $this->addContent(Html::tag('h1',null,$this->folder.' Dashboards'));

        foreach ($dashboards as $dashboard){

            $finalUrl = Url::fromPath('grafanadashboards/grafana/dashboard', ['uid'=>$dashboard['uid'],'folder'=>$this->folder,'name'=>$this->instance->name]);

            $a = Html::tag("a",['class'=>"dashboard-link",'href'=> $finalUrl]);
            $div = Html::tag("div",['class'=>"link-icon"]);
            $i = new Icon("area-chart",[ 'aria-hidden' => 1]);

            $div->add($i);
            $a->add($div);
            $div_link_meta = Html::tag("div",['class'=>"link-meta"]);
            $div_link_label = Html::tag("div",['class'=>"link-label"],$dashboard['title']);
            $div_link_description = Html::tag("div",['class'=>"link-description"],"View Dashboard {$dashboard['title']}");
            $div_link_meta->add($div_link_label);
            $div_link_meta->add($div_link_description);
            $a->add($div_link_meta);
            $this->addContent($a);

        }

    }
    protected function initTabs(): void
    {
        $tabs = $this->getTabs();
        if($this->helper !== null){
            $dashboards = $this->helper->getDashboardsByFolder($this->folder);
            if($dashboards ===false){
                return;
            }
            $dashboards = $this->permissionHelper->filterDashboards($dashboards);

            foreach ($dashboards as $dashboard){
                $finalUrl = Url::fromPath('grafanadashboards/grafana/dashboard', ['uid'=>$dashboard['uid'],'folder'=>$this->folder,'name'=>$this->instance->name]);
                $tabs
                    ->add($dashboard['uid'], [
                        'label' => $dashboard['title'],
                        'url' => $finalUrl,
                    ]);

            }
        }


    }




}
