<?php

/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\Grafanadashboards\Controllers;



use Icinga\Application\Modules\Module;
use Icinga\Module\Grafanadashboards\GrafanaHelper;

use Icinga\Module\Grafanadashboards\InstanceIniRepository;
use ipl\Web\Compat\CompatController;


class IndexController extends CompatController
{
    /* @var $helper \Icinga\Module\Grafanadashboards\GrafanaHelper */
    protected $helper;
    protected $folder;
    protected $config;
    protected $instance;
    public function init()
    {

        parent::init();
        $this->instance = $this->params->getRequired('instance');
        $instanceRepository = new InstanceIniRepository();
        $instance = $instanceRepository->select()->where($instanceRepository->getIdentifierName(),$this->instance)->fetchRow();
        if($instance !== false){
            $module = Module::get('grafanadashboards');
            $cacheDir = $module->getConfigDir().DIRECTORY_SEPARATOR."cache";
            $this->folder = $this->getParam('folder');
            if(isset($instance->url) && isset($instance->apikey)){
                $this->helper =  new GrafanaHelper(
                    $this->instance,
                    $instance->url,
                    $instance->apikey,
                    $instance->disable_ssl =='0',
                    $cacheDir
                );
            }else{
                throw new \Exception("Configure Module grafanadashboards first!");
            }
        }





    }




}
