<?php

/* Originally from Icinga Web 2 Elasticsearch Module (c) 2017 Icinga Development Team | GPLv2+ */
/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\Grafanadashboards\Controllers;

use Icinga\Application\Modules\Module;
use Icinga\Module\Grafanadashboards\JwtHelper;

use Icinga\Module\Grafanadashboards\Forms\InstanceForm;
use Icinga\Module\Grafanadashboards\InstanceIniRepository;
use ipl\Html\Html;
use ipl\Web\Compat\CompatController;
use ipl\Web\Url;
use ipl\Web\Widget\ButtonLink;

class InstanceController extends CompatController
{
    /**
     * Set the title tab
     *
     * @param   string  $label
     */
    public function setTitle($title,...$args)
    {
        $this->getTabs()->add(uniqid(), [
            'active'    => true,
            'label'     => $title,
            'url'       => $this->getRequest()->getUrl()
        ]);
    }


    public function init()
    {
        $this->assertPermission('grafanadashboards/instance/config');
    }
    public function configAction(){
        $id = $this->params->getRequired('id');
        $instance = (new InstanceIniRepository())->select()->where('name',$id)->fetchRow();
        if($instance === false){
            throw new \Exception("Instance not found");
        }
        $this->addContent(Html::tag('h1',null,"Config of"." ".$id));

        if($instance->type==="jwt"){
            $button = new ButtonLink($this->translate('Recreate Config'),Url::fromPath('grafanadashboards/instance/config',
                ['id'=>$id,'recreate'=>'yes']),'plus' );
            $this->addContent($button);
            $recreate = $this->params->get('recreate','no')==="yes";
            $module = Module::get('grafanadashboards');
            $pkiDir = $module->getConfig()->get('settings','pkidir',$module->getConfigDir().DIRECTORY_SEPARATOR."pki");
            $jwt = new JwtHelper($id,null,null,null,$pkiDir);
            $jwt->generateKeypair($recreate);
            $keyPath = $jwt->getPublicKeyPath();
            $config =
                <<<TEXT
[auth.jwt]
enabled = true
header_name = X-AUTH-TOKEN
email_claim = sub
username_claim = user
key_file = $keyPath
url_login = true 
TEXT;

            $this->addContent(Html::tag('h2',null,"grafana.ini"));
            $this->addContent(Html::tag('p',null,"Please adjust the location, if this path is not suitable"));
            $this->addContent(Html::tag('pre',null,$config));

            $this->addContent(Html::tag('h2',null,"The public key content of the above mentioned file"));
            $this->addContent(Html::tag('pre',null,$jwt->getPublicKey()));
        }else{
            $config =
                <<<TEXT
[auth]
# Login cookie name
login_cookie_name = grafana_session
...

[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
enable_login_token = true
whitelist = 127.0.0.1

[security]
...
# set to true if you want to allow browsers to render Grafana in a <frame>, <iframe>, <embed> or <object>. default is false.
allow_embedding = true
...
TEXT;
            $this->addContent(Html::tag('h2',null,"grafana.ini"));
            $this->addContent(Html::tag('p',null,"Please adjust the settings if not suitable"));
            $this->addContent(Html::tag('pre',null,$config));

        }





    }
    public function indexAction()
    {
        $this->setTitle($this->translate('Instances'));
        $this->view->configs = (new InstanceIniRepository())->select();

        $this->_helper->viewRenderer->setRender('instance/grid', null, true);
    }

    public function newAction()
    {
        $form = new InstanceForm([
            'mode'  => InstanceForm::MODE_INSERT
        ]);

        $form->handleRequest();

        $this->setTitle($this->translate('New Instance'));

        $this->view->form = $form;

        $this->_helper->viewRenderer->setRender('form', null, true);
    }

    public function updateAction()
    {
        $id = $this->params->getRequired('id');

        $form = new InstanceForm([
            'mode'          => InstanceForm::MODE_UPDATE,
            'identifier'    => $id
        ]);

        $form->handleRequest();


        $this->setTitle($this->translate('Update Instance'));

        $this->view->form = $form;

        $this->_helper->viewRenderer->setRender('form', null, true);
    }

    public function deleteAction()
    {
        $id = $this->params->getRequired('id');

        $form = new InstanceForm([
            'mode'          => InstanceForm::MODE_DELETE,
            'identifier'    => $id
        ]);

        $form->handleRequest();

        $this->setTitle($this->translate('Remove Instance'));

        $this->view->form = $form;

        $this->_helper->viewRenderer->setRender('form', null, true);
    }
}
