<?php

/* Originally from Icinga Web 2 Elasticsearch Module (c) 2017 Icinga Development Team | GPLv2+ */
/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\Grafanadashboards\Forms;

use Icinga\Data\Filter\Filter;
use Icinga\Forms\RepositoryForm;
use Icinga\Module\Grafanadashboards\InstanceIniRepository;

/**
 * Create, update and delete a Config
 */
class InstanceForm extends RepositoryForm
{
    protected $protectedFields = ['apikey'];

    public function init()
    {
        $this->repository = new InstanceIniRepository();
        $this->redirectUrl = 'grafanadashboards/instance';
        $this->repository->setProtectedFields($this->protectedFields);

    }
    /**
     * Prepare the form for the requested mode
     * Clear out protectedFields
     */
    public function fetchEntry()
    {
        $entry = parent::fetchEntry();
        if($entry != null ){
            foreach($this->protectedFields as $field){

                if( in_array($field, array_keys(get_object_vars($entry))) ){
                    $entry->{$field} =  "";
                }
            }
        }

        return $entry;
    }


    /**
     * Set the identifier
     *
     * @param   string  $identifier
     *
     * @return  $this
     */
    public function setIdentifier($identifier)
    {
        $this->identifier = $identifier;

        return $this;
    }

    /**
     * Set the mode of the form
     *
     * @param   int $mode
     *
     * @return  $this
     */
    public function setMode($mode)
    {
        $this->mode = $mode;

        return $this;
    }

    protected function onUpdateSuccess()
    {
        if ($this->getElement('btn_remove')->isChecked()) {
            $this->setRedirectUrl("grafanadashboards/instance/delete?id={$this->getIdentifier()}");
            $success = true;
        } else {
            $success = parent::onUpdateSuccess();
        }

        return $success;
    }

    protected function createBaseElements(array $formData)
    {

        $columns = (new InstanceIniRepository())->getColumnDefinitions();

        foreach ($columns as $column=>$options){
            if(is_array($options)){
                $fieldtype = $options['fieldtype']??"text";
                unset($options['fieldtype']);
                $this->addElement($fieldtype, $column, $options);
            }else{
                $this->addElement('text', $column, [
                    'label' => $options
                ]);
            }
        }


    }


    protected function createInsertElements(array $formData)
    {
        $this->createBaseElements($formData);

        $this->setTitle($this->translate('Create a New Instance'));

        $this->setSubmitLabel($this->translate('Save'));
    }

    protected function createUpdateElements(array $formData)
    {
        $this->createBaseElements($formData);

        $this->setTitle(sprintf($this->translate('Update Instance %s'), $this->getIdentifier()));

        $this->addElement(
            'submit',
            'btn_submit',
            [
                'decorators'            => ['ViewHelper'],
                'ignore'                => true,
                'label'                 => $this->translate('Save')
            ]
        );

        $this->addElement(
            'submit',
            'btn_remove',
            [
                'decorators'            => ['ViewHelper'],
                'ignore'                => true,
                'label'                 => $this->translate('Remove')
            ]
        );

        $this->addDisplayGroup(
            ['btn_submit', 'btn_remove'],
            'form-controls',
            [
                'decorators' => [
                    'FormElements',
                    ['HtmlTag', ['tag' => 'div', 'class' => 'control-group form-controls']]
                ]
            ]
        );
    }

    protected function createDeleteElements(array $formData)
    {
        $this->setTitle(sprintf($this->translate('Remove Instance %s'), $this->getIdentifier()));

        $this->setSubmitLabel($this->translate('Yes'));
    }

    protected function createFilter()
    {
        return Filter::where($this->repository->getIdentifierName(), $this->getIdentifier());
    }

    protected function getInsertMessage($success)
    {
        return $success
            ? $this->translate('Instance created')
            : $this->translate('Failed to create Instance');
    }

    protected function getUpdateMessage($success)
    {
        return $success
            ? $this->translate('Instance updated')
            : $this->translate('Failed to update Instance');
    }

    protected function getDeleteMessage($success)
    {
        return $success
            ? $this->translate('Instance removed')
            : $this->translate('Failed to remove Instance');
    }
}
